### PR TITLE
First pass at the conference landing page

### PR DESCRIPTION
**Pull request by robertlong**
This PR is for a revised landing page for IEEE VR.

The proposed design can be found here: https://www.figma.com/file/kz0G24kuNF3lyaDQQTxVPd/VR2020?node-id=1%3A2

### CODE REVIEW

**Comment by robertlong** [comment]
@blairmacintyre the landing page should be pretty much ready to go. I'd like to get that content for the landing page before we merge this.

**Comment by blairmacintyre** [comment]
How about we start with

### Welcome to IEEEVR 2020

## The Premier International Conference on Virtual Reality and 3D User Interfaces

To join the online experience, you must be registered as a conference attendee, and logged in with the same email you used to register.  Visit the [main IEEEVR 2020 Conference](http://ieeevr.org/2020) to register.  Visit the [Online Information](http://ieeevr.org/2020/online/) page for more information about the online experience, links to join our conference Slack, and an FAQ for the conference and systems we are using.  (Registration information is not immediately synchronized, so don't wait till the last minute to register.)

After signing in, please visit the Tutorial rooms if you are unfamiliar with the Hubs virtual world software. Documentation on the hubs controls for various platforms is available on the [Hubs Wiki](https://github.com/mozilla/hubs/wiki/Hubs-Controls), along with a wealth of other information that might make your IEEE VR experience using Hubs more enjoyable.

**Comment by blairmacintyre** [comment]
Did you manage to figure out a way to sort the sets of rooms?

**Comment by speigg** [comment]
Ready to merge & deploy?

**Comment by robertlong** [comment]
@speigg yeah, it should be ready now.

**Pull request merged**
